### ISSUE TITLE
PassThru repeats single module output

### ISSUE THREAD

**Issue by ThomasNieto** [JustinGrote/ModuleFast#74] opened 2024-01-28 00:30 UTC
```
Install-ModuleFast az -PassThru

Name               ModuleVersion Location
----               ------------- --------
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
Az.StreamAnalytics 2.0.0         file:///C:/Users/Thomas/AppData/Local/powershell/Modules/Az.Storage/6.1.0
```

**Comment by JustinGrote** [comment] 2024-01-28 23:20
Dupe of https://github.com/JustinGrote/ModuleFast/issues/70, use the main branch bootstrap until the next release. Thanks!

**Closed by JustinGrote** 2024-01-28 23:20 UTC
